### ISSUE TITLE
Send callback bug

### ISSUE THREAD

**Issue by Sincrono01** [Elytrium/VelocityTools#10]
![image](https://user-images.githubusercontent.com/85366568/185360371-0ba6f3c4-7012-47c4-8c2a-93bd86bf2cd7.png)
Hi, I'm using VelocityTools 1.1.7 (currently the last version) and Velocity 3.1.2 and when I use the /send command the callback message keeps saying me that I'm moving 0 players to the other server, but that isn't true
![image](https://user-images.githubusercontent.com/85366568/185361165-7984424b-f782-41db-b779-d5f6e2b67976.png)

**Comment by Galster-dev** [comment]
Can confirm, using latest velocity & velocity tools build
