### ISSUE TITLE
Error while connecting to server

### ISSUE THREAD

**Issue by nazmiyigitefe** [Elytrium/VelocityTools#20]
I could not connect my server while VelocityTools installed, if i remove it i can easily connect.

Error: 
![image](https://user-images.githubusercontent.com/71214979/229129718-b5a5fb26-b5d1-41ec-a319-cd2569e2ea1d.png)

Velocity Version: Build 246
Client Version: 1.16.5

**Comment by hevav** [comment]
Read the config.
