### ISSUE TITLE
Velocity appears Offline and gives `Disconnected`

### ISSUE THREAD

**Issue by C0D3-M4513R** [Elytrium/VelocityTools#21]
Velocity server appears as offline, and connecting to it just gives `Disconnected`.
velocity-3.2.0-SNAPSHOT-258
velocity_tools-1.1.9.jar
ambassador: 1.4.0

Also using ViaVersion 4.7.0 and ViaBackwards 4.7.0 on Velocity and Lobby (Paper)

**Comment by dimadencep** [comment]
Fixed by ambassador

**Comment by dimadencep** [comment]
Ye

**Comment by mdxd44** [comment]
And a tip: don't use via* plugins on proxy.
