### ISSUE TITLE
VelocityTools unreigsters commands from other plugins if in hub aliases

### ISSUE THREAD

**Issue by ajgeiss0702** [Elytrium/VelocityTools#23]
It looks like VelocityTools unregisters hub aliases, even if it didn't register them in the first place.

This causes issues with other plugins that register commands with the name of one of the aliases, as VelocityTools just unregisters them.

Here is where the issue appears to happen: https://github.com/Elytrium/VelocityTools/blob/master/src/main/java/net/elytrium/velocitytools/VelocityTools.java#L141

For example, users in my plugin can set slash-server commands. So, for example, `/hub` will cause the player to queue for the hub server. A user of my plugin was wanting to use that feature. They disabled VelocityTool's hub feature, and configured `/hub` in my plugin, however they found that most of the time the command would not work. After some investigation, it was found that if the server name is in the `aliases` list of VelocityTool's hub feature, then VelocityTools unregisters the command whenever it is (re)loaded.

A quick fix is to empty the list of aliases in the config, but I believe a fix should be implemented in VelocityTools that will prevent unregistering other plugins' commands

**Comment by mdxd44** [comment]
<img src="https://github.com/Elytrium/VelocityTools/assets/67416904/cb7b5190-0d14-4b9b-aceb-a82d07c363f3" width="64">

**Comment by mdxd44** [comment]
fixed in eb161f3
