### ISSUE TITLE
VERSIONS

### ISSUE THREAD

**Issue by HonzasikCZ** [Elytrium/VelocityTools#41]
When I connect with an unsupported version I set to 1.13 it shows the message I set but when I connect with a version lower than 1.13 it shows the message from velocity.

![obrazek](https://github.com/Elytrium/VelocityTools/assets/94143975/97fcbf88-1f5b-4755-8688-d6d9eae69977)
(The message is in Czech)

I want it to show the message I set in the velocity tools config. Is there any way to do this? Otherwise, thank you for reading <3

**Comment by mdxd44** [comment]
velocity.error.modern-forwarding-needs-new-client in your_proxy_dir/lang/messages.properties
