### ISSUE TITLE
[BUG] hostnames-manager does not work, block-join: true

### ISSUE THREAD

**Issue by Watghi** [Elytrium/VelocityTools#7]
For some reason, it is still possible to log in to a different IP address

**Comment by mdxd44** [comment]
> For some reason, it is still possible to log in to a different IP address

Enable debug and check which hostname the client is sending

**Comment by Watghi** [comment]
Is it normal that I'm trying to log in from a digital IP address, and debug says that I'm logging in from a domain?


[02:37:09 INFO] [velocity_tools]: /1.1.1.1:50190 is pinging the server using: 127.2.2.2 (blocked)
[02:37:11 INFO] [velocity_tools]: /1.1.1.1:50196 is joining the server using: domain.net
[02:37:12 INFO]: [connected player] Nickname (/1.1.1.1:50196) has connected
[02:37:12 INFO]: [server connection] Nickname -> hub has connected
[02:37:12 INFO]: [server connection] Nickname -> hub has disconnected

**Comment by mdxd44** [comment]
> Is it normal that I'm trying to log in from a digital IP address, and debug says that I'm logging in from a domain?
> 
> [02:37:09 INFO] [velocity_tools]: /1.1.1.1:50190 is pinging the server using: 127.2.2.2 (blocked) [02:37:11 INFO] [velocity_tools]: /1.1.1.1:50196 is joining the server using: domain.net [02:37:12 INFO]: [connected player] Nickname (/1.1.1.1:50196) has connected [02:37:12 INFO]: [server connection] Nickname -> hub has connected [02:37:12 INFO]: [server connection] Nickname -> hub has disconnected

The hostname is sent by the client itself in the handshake packet, there is nothing we can do about it.

**Comment by Watghi** [comment]
Okay, goodbye
